apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: {{ .Values.ingressIdentifier }}
    external-dns.alpha.kubernetes.io/aws-weight: "100"
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      SecRuleEngine On
      SecDefaultAction "phase:2,pass,log,tag:github_team=webops"
      SecDefaultAction "phase:4,pass,log,tag:github_team=webops"
spec:
  tls:
    - hosts:
        - modules.apps.{{ .Values.cluster }}.cloud-platform.service.justice.gov.uk
  rules:
    - host: modules.apps.{{ .Values.cluster }}.cloud-platform.service.justice.gov.uk
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: api
                port:
                  number: 3001
  ingressClassName: modsec
