apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 2
  selector:
    matchLabels:
      name: api
  template:
    metadata:
      labels:
        name: api
    spec:
      containers:
        - name: application
          image: jaskaransarkaria/cloud-platform-go-get-module:VERSION
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: REDIS_SECRET
              valueFrom:
                secretKeyRef:
                  name: redis-helm
                  key: redis-password
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: go-get-module-api-key
                  key: api_key
            - name: REDIS_ADDR
              value: "redis-helm-master.cloud-platform-go-get-module.svc.cluster.local" 
            - name: GIN_MODE
              value: "release"
