apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  redis-config: |
    maxmemory 2mb
    maxmemory-policy allkeys-lru
  redis-master-addr: "redis-helm-master.cloud-platform-go-get-module.svc.cluster.local" 
