name: Build and Push

on:
  workflow_call:
    inputs:
      env:
        description: 'which environment to deploy to'
        required: true
        type: string
      image_tag:
        description: 'what to tag the image with'
        type: string
      ecr_repo:
        description: 'name of the ecr repo'
        required: true
        type: string
      aws_region:
        description: 'region of the ecr repo'
        type: string
        required: true
    secrets:
      ecr_role_to_assume:
        description: 'ecr role to assume in aws'
        required: true
      ecr_url:
        description: 'the url for the ecr repo, where the image is pulled from'
        required: true

jobs:
  my-jobname:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo ${{secrets.ecr_role_to_assume}} | sed 's/./& /g'


  build-and-push:
    name: Build container, push to ECR and deploy to the cluster
    environment: ${{ inputs.env }}
    runs-on: ubuntu-latest
    outputs:
      IMAGE_TAG: ${{ steps.build-image.outputs.IMAGE_TAG }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ecr_role_to_assume }}
          aws-region: ${{ inputs.aws_region }}

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REPO: ${{ inputs.ecr_repo }}
          ECR_URL: ${{ secrets.ecr_url }}
          IMAGE_TAG: ${{ inputs.image_tag }}
        run: |
          aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin $ECR_URL 
          docker build -t $ECR_REPO:$IMAGE_TAG .
          docker tag $ECR_REPO:$IMAGE_TAG $ECR_URL:$IMAGE_TAG
          docker push $ECR_URL:$IMAGE_TAG
