name: Build and push a new dev release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-push:
    uses: ./.github/workflows/build-and-push-workflow.yaml
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout
    with:
      env: development
      image_tag: ${{ github.sha }}
      ecr_repo: webops/cloud-platform-go-get-module-ecr
      aws_region: eu-west-2
    secrets:
      ecr_role_to_assume: ${{ secrets.ECR_ROLE_TO_ASSUME }}

  deploy:
    needs: build-and-push
    uses: ./.github/workflows/deploy-workflow.yaml
    with:
      env: development
      image_tag: ${{ github.sha }}
    secrets:
      ecr_url: "${{ needs.build-and-push.outputs.REGISTRY }}/webops/cloud-platform-go-get-module-ecr"

