name: Build and push a new dev release

on:
  push:
    branches:
      - main

permissions:
  contents: write

env:
  ECR_ROLE_TO_ASSUME: ${{ secrets.ECR_ROLE_TO_ASSUME }}

jobs:
  build-and-push:
    uses: ./.github/workflows/build-and-push-workflow.yaml
    with:
      env: development
      image_tag: ${{ github.sha }}
      ecr_repo: webops/cloud-platform-go-get-module-ecr
      aws_region: eu-west-2
    secrets:
      ecr_role_to_assume: ${ env.ECR_ROLE_TO_ASSUME }}
      ecr_url: ${{ secrets.ECR_URL }}

  deploy:
    needs: build-and-push
    uses: ./.github/workflows/deploy-workflow.yaml
    with:
      env: development
      image_tag: ${{ github.sha }}
    secrets:
      kube_namespace: "${{ secrets.KUBE_NAMESPACE }}"
      kube_cert: "${{ secrets.KUBE_CERT }}"
      kube_cluster: "${{ secrets.KUBE_CLUSTER }}"
      kube_token: "${{ secrets.KUBE_TOKEN }}"
      ecr_url: "${{ secrets.ECR_URL }}"

